# These volumes record all persistent data for the Test Bed instance.
volumes:
  gitb-repo:
  gitb-dbdata:
  

services:
  # HL7 FHIR Validator CLI running as an HTTP service
  fhir-validator:
#    image: costateixeira/fhir-validator:6.8.3
    build: fhir-validator
    container_name: itb-fhir-validator
    restart: unless-stopped
    ports:
      - "8088:8081"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -X POST http://localhost:8081/validateResource -H 'Content-Type: application/fhir+json' -d '{\"resourceType\":\"Patient\"}' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  gitb-redis:
    # Internal component used to store users' UI sessions.
    image: redis:7.2.5
    container_name: itb-redis    
    restart: unless-stopped

  gitb-mysql:
    # The Test Bed's DB.
    image: isaitb/gitb-mysql:latest
    container_name: itb-mysql    
    restart: unless-stopped
    volumes:
      - gitb-dbdata:/var/lib/mysql
    # We use a healthcheck to make sure the DB is up and running before we try to connect to it (this could
    # take a few seconds after the container is up and running).
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      retries: 10

  gitb-srv:
    # The test engine that executes the test sessions.
    # Note that this (and the gitb-ui container) point to the "nightly" tag which receives updates based on our
    # development branch. In production this would be "latest" or a fixed release tag.
    image: isaitb/gitb-srv:latest
    container_name: itb-srv
    restart: unless-stopped
    environment:
      # This is used to define how external services (the fhir-test-services component) will make callbacks on the
      # test engine. The address here must be what the fhir-test-services component should use for the calls.
      # If you deploy the fhir-test-services outside the docker-compose service you would need to adapt this. For
      # example you would add a port mapping for port 8080 (this is currently not mapped to the host) and then
      # refer to an address such as "localhost".
      - gitb.messaging.callbackURL=http://gitb-srv:8080/itbsrv/MessagingClient

  gitb-ui:
    # The Test Bed's UI.
    image: isaitb/gitb-ui:latest
    container_name: itb-ui    
    restart: unless-stopped
    # This is the only Test Bed component for which we currently add a host port mapping. If port 9000 on your
    # host is taken just replace "9000:9000" with say "9001:9000".
    ports:
      - "9000:9000"
    environment:
      # This is the key to decrypt the initialisation data archive (see below).
      - DATA_ARCHIVE_KEY=fhir
      # This is the key to decrypt the initialisation data archive (see below).
      - DATA_ARCHIVE_KEY=fhir
      # Flag to enable the Test Bed's REST API. This can be very useful for efficient test case development.
      - AUTOMATION_API_ENABLED=true
      # Activate the generic vitalink theme.
      - THEME=vitalink
    volumes:
      - gitb-repo:/gitb-repository
      # This points to the folder from which the initialisation data archive specific to the PoC will be loaded from.
      - ./config/data/:/gitb-repository/data/in/:rw
    depends_on:
      gitb-redis:
        condition: service_started
      gitb-mysql:
        condition: service_healthy
      gitb-srv:
        condition: service_started


  fhir-server-sut:
    # This is a second FHIR server that is used as part of the PoC to serve as a system under test (SUT) for the test
    # cases verifying FHIR servers.
    #
    # Outside the scope of the PoC this service can be deleted, to be replaced with actual external FHIR server instances
    # (the ones that are being tested).
    image: hapiproject/hapi:latest
    restart: unless-stopped
    environment:
      - fhir_version=R4
      - server_port=8080
      - static_server_port=9003
      - server_name=AllergyTB      
      - hapi.fhir.allow_multiple_delete=true
      - hapi.fhir.server_address=localhost:8080
      - hapi.fhir.reuse_cached_search_results_millis=-1
      - hapi.fhir.cors.allow_Credentials=true
      - hapi.fhir.cors.allowed_origin_patterns="http:localhost:*"
      - hapi.fhir.ig_runtime_upload_enabled=true
      - hapi.fhir.custom_content_path=/custom
      - hapi.fhir.app_content_path=/apps
    volumes:
      - ./config/fhir/custom:/custom
      - ./config/fhir/apps:/apps
    ports:
      - 9003:8080